### ISSUE TITLE
Callback should also have a success callback

### ISSUE THREAD

**Issue by imixtron** [Dvs-Bilisim/backup-manager#2]
Right now the callback only handles the error if there is any, it should also return the filename when its created.

p.s. if you are accepting any contribution i am available for it.

**Comment by umuplus** [comment]
I am not sure if we need another callback for success. 

Current callback takes 1 parameter. if there is an error, you can access it directly from callback. Otherwise that parameter would be undefined and that means it's OK to proceed.

```js
mongo.backup([ '--host localhost', '--db test', '--gzip' ], error => {
     if (error) console.log(error);

     // Otherwise everything is OK to proceed.
});
```

Of course I'm open for contribution when it's useful. I am planning to add same features for MySQL, PostgreSQL, etc.
Thank you for your feedback again.

**Comment by miladr0** [comment]
how to get file name on success?
