### ISSUE TITLE
Sanatize options sent to command

### ISSUE THREAD

**Issue by imixtron** [Dvs-Bilisim/backup-manager#5]
The options that are sent to `_command` method are not sanatized which sometimes breaks the mongodump shell command.

https://github.com/Dvs-Bilisim/backup-manager/blob/a517bc4f27aa117020c1e646bff4798e0b8697bd/src/mongodb.js#L32

https://github.com/Dvs-Bilisim/backup-manager/blob/a517bc4f27aa117020c1e646bff4798e0b8697bd/src/base.js#L141-L146

**How to reproduce**
```javascript
const mongo = new MongoDB({ debug: true, path: '/tmp/backup' });
mongo.dump([ '--host localhost', '--db test', '--gzip', '--mycustarg broken' ], error => console.log(error));
```

```sh
mongodump --host localhost --db test --gzip --mycustarg broken
2018-12-29T15:29:44.910+0500    error parsing command line options: unknown option "mycustarg"
2018-12-29T15:29:44.911+0500    try 'mongodump --help' for more information
```

**Comment by umuplus** [comment]
I think there is a misunderstanding about "sanatizing options".
Old version had a bad way to build the correct shell command out of options and bin parameters that you can see in [history of src/base.js](https://github.com/Dvs-Bilisim/backup-manager/commit/9c659d781b4925faaf19db4884403cadb4dbe72f#diff-d7e697eff3913f1acaacac8002c3b05eL148).

You can also see the usage of it in [history of tests/backup.](https://github.com/Dvs-Bilisim/backup-manager/commit/9c659d781b4925faaf19db4884403cadb4dbe72f#diff-5dcf4e305e2fec0cda1177114f4a3e85L39)test

Instead of that approach, I implemented a simple array based command builder. But that implementation doesn't check parameters. If any error occurs, it returns the error back so you can be aware of what's going on and fix the issue.
